defmodule QuantumBilling.EInvoice.Payload do
  @moduledoc """
  Builds the INV-01 element tree for an invoice.

  ## Why INV-01, rendered as XML

  The GST e-invoice schema is canonically JSON. Emitting its element names and
  nesting as XML means a later integration with a GSP is a mechanical tree-to-
  JSON transform of this same builder, rather than a rewrite. UBL 2.1 was the
  alternative and is a dead end here: GSTN does not use it and no Indian GSP
  consumes it.

  ## This is not a registered e-invoice

  A document becomes an e-invoice when the Invoice Registration Portal returns an
  IRN and a digitally signed QR. Neither can be produced offline, so neither
  appears here — see `QuantumBilling.EInvoice` for what this is for.

  ## Text nodes, not bare strings

  Every value goes out as `{:characters, _}`. `Saxy.encode!/2` emits a bare
  binary child verbatim, so a client called "Smith & Sons" would otherwise
  produce a file no parser will read.
  """

  alias QuantumBilling.GST
  alias QuantumBilling.Invoices.Invoice
  alias QuantumBilling.Invoices.InvoiceItem
  alias QuantumBilling.Settings.Organization

  @version "1.1"

  # The document types the schema knows. A Bill of Supply and an Export Invoice
  # are deliberately absent — see `EInvoice.validate/2`.
  @types %{
    "Tax Invoice" => "INV",
    "Credit Note" => "CRN",
    "Debit Note" => "DBN"
  }

  @doc "The document type code for an invoice type, or `nil` if it has none."
  def type_code(invoice_type), do: Map.get(@types, invoice_type)

  @doc "Every invoice type that can be exported."
  def exportable_types, do: Map.keys(@types)

  @doc """
  The `Saxy` simple-form tree for `invoice`, issued by `organization`.

  Assumes `EInvoice.validate/2` has already passed; it builds what it is given.
  """
  def build(%Invoice{} = invoice, %Organization{} = organization) do
    {"Invoice", [],
     [
       comment(invoice),
       element("Version", @version),
       tran_details(invoice),
       doc_details(invoice),
       seller_details(organization),
       buyer_details(invoice),
       item_list(invoice),
       value_details(invoice)
     ]}
  end

  # In the file itself, not only in the UI: whoever opens this months from now
  # will not have the screen that produced it in front of them.
  defp comment(invoice) do
    {:comment,
     "\n  GST e-invoice (INV-01) data for #{invoice.invoice_number}, rendered as XML.\n" <>
       "  This is NOT a registered e-invoice: it carries no IRN and no signed QR,\n" <>
       "  because only the Invoice Registration Portal can issue those. Generated by\n" <>
       "  QuantumBilling for record-keeping and for handing to a GSP or an accountant.\n"}
  end

  defp tran_details(invoice) do
    {"TranDtls", [],
     [
       element("TaxSch", "GST"),
       element("SupTyp", supply_type(invoice)),
       element("RegRev", "N")
     ]}
  end

  # B2B when the buyer is registered, B2C when they are not. The distinction is
  # the buyer's GSTIN and nothing else.
  defp supply_type(%Invoice{client_gstin: gstin}) do
    if GST.valid_gstin?(gstin), do: "B2B", else: "B2C"
  end

  defp doc_details(invoice) do
    {"DocDtls", [],
     [
       element("Typ", type_code(invoice.invoice_type)),
       element("No", invoice.invoice_number),
       element("Dt", date(invoice.invoice_date))
     ]}
  end

  defp seller_details(organization) do
    {"SellerDtls", [],
     [
       element("Gstin", organization.gstin),
       element("LglNm", organization.company_name),
       maybe("TrdNm", organization.trade_name),
       element("Addr1", first_line(organization.address)),
       maybe("Addr2", rest_lines(organization.address)),
       element("Loc", organization.city),
       element("Pin", organization.pincode),
       element("Stcd", GST.state_code(organization.state))
     ]
     |> compact()}
  end

  # From the invoice's snapshot, never from the client record: the buyer on a
  # tax document is who it was billed to at the time.
  defp buyer_details(invoice) do
    {"BuyerDtls", [],
     [
       maybe("Gstin", if(GST.valid_gstin?(invoice.client_gstin), do: invoice.client_gstin)),
       element("LglNm", invoice.client_name),
       element("Pos", GST.state_code(invoice.place_of_supply)),
       element("Addr1", first_line(invoice.client_billing_address)),
       maybe("Addr2", rest_lines(invoice.client_billing_address)),
       element("Loc", invoice.client_city),
       element("Pin", invoice.client_pincode),
       element("Stcd", GST.state_code(invoice.client_state) || GST.state_code(invoice.place_of_supply))
     ]
     |> compact()}
  end

  defp item_list(invoice) do
    intra_state? = Invoice.intra_state?(invoice)

    items =
      invoice.items
      |> Enum.with_index(1)
      |> Enum.map(fn {item, index} -> item(item, index, intra_state?) end)

    {"ItemList", [], items}
  end

  defp item(%InvoiceItem{} = item, index, intra_state?) do
    amount = InvoiceItem.amount(item)
    tax = InvoiceItem.tax(item)
    {cgst, sgst, igst} = split(tax, intra_state?)

    {"Item", [],
     [
       element("SlNo", Integer.to_string(index)),
       element("PrdDesc", item.description),
       # The schema wants goods or services. Nothing on the form records which,
       # and a SAC is what a service carries, so the HSN/SAC code decides it:
       # service accounting codes begin with 99.
       element("IsServc", if(service?(item.hsn_sac), do: "Y", else: "N")),
       element("HsnCd", item.hsn_sac),
       element("Qty", Integer.to_string(item.quantity || 0)),
       element("Unit", unit_code(item.unit)),
       element("UnitPrice", decimal(item.rate)),
       element("TotAmt", decimal(amount)),
       element("AssAmt", decimal(amount)),
       element("GstRt", decimal(item.tax_rate)),
       element("CgstAmt", decimal(cgst)),
       element("SgstAmt", decimal(sgst)),
       element("IgstAmt", decimal(igst)),
       element("TotItemVal", decimal(amount + tax))
     ]}
  end

  defp value_details(invoice) do
    {"ValDtls", [],
     [
       element("AssVal", decimal(invoice.taxable_value)),
       element("CgstVal", decimal(invoice.cgst_amount)),
       element("SgstVal", decimal(invoice.sgst_amount)),
       element("IgstVal", decimal(invoice.igst_amount)),
       element("CesVal", decimal(invoice.cess_amount)),
       element("RndOffAmt", decimal(invoice.round_off)),
       element("TotInvVal", decimal(invoice.grand_total))
     ]}
  end

  # Which tax applies is the supply's business, not the document's — the same
  # rule the renderer enforces, for the same reason.
  defp split(tax, true), do: {div(tax, 2), tax - div(tax, 2), 0}
  defp split(tax, false), do: {0, 0, tax}

  defp service?(hsn) when is_binary(hsn), do: String.starts_with?(hsn, "99")
  defp service?(_hsn), do: false

  # The schema's unit codes, which are not the labels the form offers.
  @units %{
    "Nos" => "NOS",
    "Kg" => "KGS",
    "Ltr" => "LTR",
    "Mtr" => "MTR",
    "Box" => "BOX",
    "Set" => "SET",
    "Pcs" => "PCS",
    "Hrs" => "HRS"
  }

  defp unit_code(unit), do: Map.get(@units, unit, "OTH")

  # dd/mm/yyyy, which is what INV-01 specifies — not the ISO form Ecto stores.
  defp date(%Date{} = date), do: Calendar.strftime(date, "%d/%m/%Y")
  defp date(_other), do: ""

  # Whole rupees in, two decimals out. Deliberately not shared with the CSV
  # export's identical-looking helper: one serves a spreadsheet and one serves a
  # schema, and coupling them would mean a change for one silently altering the
  # other.
  defp decimal(nil), do: "0.00"
  defp decimal(amount) when is_integer(amount), do: :erlang.float_to_binary(amount * 1.0, decimals: 2)

  defp first_line(nil), do: ""

  defp first_line(address) do
    address |> String.split("\n", parts: 2) |> List.first() |> String.trim()
  end

  defp rest_lines(nil), do: nil

  defp rest_lines(address) do
    case String.split(address, "\n", parts: 2) do
      [_first, rest] -> rest |> String.replace("\n", ", ") |> String.trim()
      _only_one -> nil
    end
  end

  defp element(name, value), do: {name, [], [{:characters, to_string(value || "")}]}

  defp maybe(_name, blank) when blank in [nil, ""], do: nil
  defp maybe(name, value), do: element(name, value)

  defp compact(children), do: Enum.reject(children, &is_nil/1)
end
