defmodule QuantumBillingWeb.InvoicePdfHTML do
  @moduledoc """
  The printable invoice rendered by `InvoicePdfController`.

  Self-contained: the stylesheet is generated by `InvoiceDoc.Stylesheet` and
  inlined rather than pulled from `app.css`, because this page is meant to
  survive being printed, saved and reopened without the rest of the application
  around it.

  It holds no formatting helpers of its own. It used to carry `money/1`,
  `line_amount/1` and delegations for the heading and the cess rule, which is
  how the printed document came to format its line figures differently from the
  screen and to compute a line total by a second route. Both documents now come
  out of one renderer, so there is nothing left here to disagree with.
  """
  use QuantumBillingWeb, :html

  alias QuantumBillingWeb.InvoiceDoc.Renderer

  embed_templates "invoice_pdf_html/*"
end
