defmodule QuantumBillingWeb.ReportsController do
  @moduledoc """
  Downloads for the Reports page.

  The export takes the same filter parameters the LiveView holds, so the file a
  user gets always matches the figures they were looking at.
  """
  use QuantumBillingWeb, :controller

  alias QuantumBilling.Reports

  @headers ["Tax Type", "Taxable Value", "CGST", "SGST", "IGST", "Total Tax"]
  @sales_register_headers [
    "Date",
    "Invoice Number",
    "Client",
    "GSTIN",
    "Status",
    "Tax Type",
    "Taxable Value",
    "CGST",
    "SGST",
    "IGST",
    "Cess",
    "Total Tax",
    "Grand Total"
  ]

  def export(conn, params) do
    filters = filters_from(params)

    {headers, rows, prefix} =
      if filters.report_type == "Sales Register" do
        rows =
          Reports.invoices()
          |> Reports.filter(filters)
          |> sales_register_rows()

        {@sales_register_headers, rows, "gst-sales-register"}
      else
        rows =
          Reports.invoices()
          |> Reports.filter(filters)
          |> Reports.tax_summary()
          |> tax_summary_rows()

        {@headers, rows, "gst-tax-summary"}
      end

    csv = to_csv(headers, rows)
    send_download(conn, {:binary, csv}, filename: filename(prefix, filters))
  end

  defp filters_from(params) do
    Reports.default_filters()
    |> Map.put(:date_range, param(params, "date_range", "This Year"))
    |> Map.put(:report_type, param(params, "report_type", "All Reports"))
    |> Map.put(:client, param(params, "client", "All Clients"))
    |> Map.put(:status, param(params, "status", "All Status"))
    |> Map.put(:gstin, param(params, "gstin", ""))
  end

  defp param(params, key, default) do
    case Map.get(params, key) do
      value when is_binary(value) -> value
      _missing_or_nested -> default
    end
  end

  defp tax_summary_rows(tax_summary) do
    Enum.map(tax_summary, fn row ->
      [
        row.label,
        amount(row.taxable_value),
        amount(row.cgst),
        amount(row.sgst),
        amount(row.igst),
        amount(row.total_tax)
      ]
    end)
  end

  defp sales_register_rows(invoices) do
    Enum.map(invoices, fn row ->
      total_tax = row.cgst + row.sgst + row.igst + row.cess
      grand_total = row.taxable_value + total_tax

      [
        QuantumBillingWeb.Format.format_date(row.date),
        to_string(row[:number] || ""),
        row.client,
        row.gstin,
        row.status,
        row.tax_type,
        amount(row.taxable_value),
        amount(row.cgst),
        amount(row.sgst),
        amount(row.igst),
        amount(row.cess),
        amount(total_tax),
        amount(grand_total)
      ]
    end)
  end

  # Plain numbers, not the ₹-prefixed display strings: a spreadsheet has to be
  # able to sum this column.
  defp amount(nil), do: ""
  defp amount(rupees), do: :erlang.float_to_binary(rupees * 1.0, decimals: 2)

  defp filename(prefix, filters) do
    slug =
      filters.date_range
      |> String.downcase()
      |> String.replace(~r/[^a-z0-9]+/, "-")

    "#{prefix}-#{slug}.csv"
  end

  # A dependency-free writer. The data is generated by this application rather
  # than supplied by a user, but quoting is still handled properly so a client
  # name containing a comma cannot shift every following column.
  defp to_csv(headers, rows) do
    [headers | rows]
    |> Enum.map_join("\r\n", fn row -> Enum.map_join(row, ",", &escape/1) end)
    |> Kernel.<>("\r\n")
  end

  defp escape(field) do
    if String.contains?(field, [",", "\"", "\n", "\r"]) do
      ~s("#{String.replace(field, "\"", "\"\"")}")
    else
      field
    end
  end
end
