defmodule QuantumBillingWeb.ReportsController do
  @moduledoc """
  Downloads for the Reports page.

  The export takes the same filter parameters the LiveView holds, so the file a
  user gets always matches the figures they were looking at.
  """
  use QuantumBillingWeb, :controller

  alias QuantumBilling.Reports

  @headers ["Tax Type", "Taxable Value", "CGST", "SGST", "IGST", "Total Tax"]
  @sales_register_headers [
    "Date",
    "Invoice Number",
    "Client",
    "GSTIN",
    "Status",
    "Tax Type",
    "Taxable Value",
    "CGST",
    "SGST",
    "IGST",
    "Cess",
    "Total Tax",
    "Grand Total"
  ]

  @doc """
  Streams the filtered report as a CSV download.

  A sales register is sent as chunks straight from a database cursor: the rows
  never all exist at once, in the database result, in this process, or in the
  response buffer. Building the whole file in memory first — which is what
  `send_download/3` does — is fine for a summary of a handful of rows and is a
  way to run a server out of memory on a year of invoices.
  """
  def export(conn, params) do
    filters = filters_from(params)

    if filters.report_type == "Sales Register" do
      stream_sales_register(conn, filters)
    else
      rows =
        filters
        |> Reports.aggregate()
        |> Map.fetch!(:tax_rows)
        |> tax_summary_rows()

      send_download(conn, {:binary, to_csv(@headers, rows)},
        filename: filename("gst-tax-summary", filters)
      )
    end
  end

  defp stream_sales_register(conn, filters) do
    conn =
      conn
      |> put_resp_content_type("text/csv")
      |> put_resp_header(
        "content-disposition",
        ~s(attachment; filename="#{filename("gst-sales-register", filters)}")
      )
      |> send_chunked(200)

    {:ok, conn} =
      Reports.stream_rows(filters, fn rows ->
        rows
        |> Stream.map(&csv_line(sales_register_row(&1)))
        |> Enum.reduce_while(chunk!(conn, csv_line(@sales_register_headers)), fn line, conn ->
          case chunk(conn, line) do
            {:ok, conn} -> {:cont, conn}
            # The browser went away mid-download. Stop reading rather than
            # finish streaming a file nobody is receiving.
            {:error, :closed} -> {:halt, conn}
          end
        end)
      end)

    conn
  end

  defp chunk!(conn, data) do
    {:ok, conn} = chunk(conn, data)
    conn
  end

  defp filters_from(params) do
    Reports.default_filters()
    |> Map.put(:date_range, param(params, "date_range", "This Year"))
    |> Map.put(:report_type, param(params, "report_type", "All Reports"))
    |> Map.put(:client, param(params, "client", "All Clients"))
    |> Map.put(:status, param(params, "status", "All Status"))
    |> Map.put(:gstin, param(params, "gstin", ""))
  end

  defp param(params, key, default) do
    case Map.get(params, key) do
      value when is_binary(value) -> value
      _missing_or_nested -> default
    end
  end

  defp tax_summary_rows(tax_summary) do
    Enum.map(tax_summary, fn row ->
      [
        row.label,
        amount(row.taxable_value),
        amount(row.cgst),
        amount(row.sgst),
        amount(row.igst),
        amount(row.total_tax)
      ]
    end)
  end

  defp sales_register_row(row) do
    total_tax = row.cgst + row.sgst + row.igst + row.cess
    grand_total = row.taxable_value + total_tax

    [
      QuantumBillingWeb.Format.format_date(row.date),
      to_string(row[:number] || ""),
      row.client,
      row.gstin,
      row.status,
      row.tax_type,
      amount(row.taxable_value),
      amount(row.cgst),
      amount(row.sgst),
      amount(row.igst),
      amount(row.cess),
      amount(total_tax),
      amount(grand_total)
    ]
  end

  # Plain numbers, not the ₹-prefixed display strings: a spreadsheet has to be
  # able to sum this column.
  defp amount(nil), do: ""
  defp amount(rupees), do: :erlang.float_to_binary(rupees * 1.0, decimals: 2)

  defp filename(prefix, filters) do
    slug =
      filters.date_range
      |> String.downcase()
      |> String.replace(~r/[^a-z0-9]+/, "-")

    "#{prefix}-#{slug}.csv"
  end

  # A dependency-free writer. The data is generated by this application rather
  # than supplied by a user, but quoting is still handled properly so a client
  # name containing a comma cannot shift every following column.
  defp to_csv(headers, rows) do
    Enum.map_join([headers | rows], "", &csv_line/1)
  end

  defp csv_line(fields) do
    Enum.map_join(fields, ",", &escape/1) <> "\r\n"
  end

  defp escape(field) do
    if String.contains?(field, [",", "\"", "\n", "\r"]) do
      ~s("#{String.replace(field, "\"", "\"\"")}")
    else
      field
    end
  end
end
