defmodule QuantumBillingWeb.ReportsController do
  @moduledoc """
  Downloads for the Reports page.

  The export takes the same filter parameters the LiveView holds, so the file a
  user gets always matches the figures they were looking at.
  """
  use QuantumBillingWeb, :controller

  alias QuantumBilling.Reports

  @headers ["Tax Type", "Taxable Value", "CGST", "SGST", "IGST", "Total Tax"]

  def export(conn, params) do
    filters = filters_from(params)

    csv =
      Reports.invoices()
      |> Reports.filter(filters)
      |> Reports.tax_summary()
      |> rows()
      |> to_csv()

    send_download(conn, {:binary, csv}, filename: filename(filters))
  end

  defp filters_from(params) do
    Reports.default_filters()
    |> Map.put(:date_range, param(params, "date_range", "This Year"))
    |> Map.put(:report_type, param(params, "report_type", "All Reports"))
    |> Map.put(:client, param(params, "client", "All Clients"))
    |> Map.put(:status, param(params, "status", "All Status"))
    |> Map.put(:gstin, param(params, "gstin", ""))
  end

  defp param(params, key, default) do
    case Map.get(params, key) do
      value when is_binary(value) -> value
      _missing_or_nested -> default
    end
  end

  defp rows(tax_summary) do
    Enum.map(tax_summary, fn row ->
      [
        row.label,
        amount(row.taxable_value),
        amount(row.cgst),
        amount(row.sgst),
        amount(row.igst),
        amount(row.total_tax)
      ]
    end)
  end

  # Plain numbers, not the ₹-prefixed display strings: a spreadsheet has to be
  # able to sum this column.
  defp amount(nil), do: ""
  defp amount(rupees), do: :erlang.float_to_binary(rupees * 1.0, decimals: 2)

  defp filename(filters) do
    slug =
      filters.date_range
      |> String.downcase()
      |> String.replace(~r/[^a-z0-9]+/, "-")

    "gst-tax-summary-#{slug}.csv"
  end

  # A dependency-free writer. The data is generated by this application rather
  # than supplied by a user, but quoting is still handled properly so a client
  # name containing a comma cannot shift every following column.
  defp to_csv(rows) do
    [@headers | rows]
    |> Enum.map_join("\r\n", fn row -> Enum.map_join(row, ",", &escape/1) end)
    |> Kernel.<>("\r\n")
  end

  defp escape(field) do
    if String.contains?(field, [",", "\"", "\n", "\r"]) do
      ~s("#{String.replace(field, "\"", "\"\"")}")
    else
      field
    end
  end
end
