defmodule QuantumBillingWeb.InvoiceDoc.Layout do
  @moduledoc """
  Reads and writes the XML an invoice layout is stored as.

  ## Escaping is Saxy's job, not ours

  Every text value goes out as a `{:characters, _}` node and every attribute
  through Saxy's encoder, so a client name containing `&` or a footer containing
  `<` produces a document that parses back to the same string. A raw binary
  child would be emitted *unescaped* by `Saxy.encode!/2` and silently produce a
  layout nothing can read — so text content is never passed as a bare string.

  ## Indentation is deliberate whitespace, not a pretty-printer

  Saxy has no pretty-printer. The newline-and-indent strings between elements
  are ordinary character nodes placed by `nl/1`; on the way back in they are
  ignored, because `elements/1` keeps only element tuples. This buys readable
  layouts and legible diffs without anyone hand-rolling an XML writer.

  ## The round trip is byte-stable

  Attributes are emitted in the order `Catalog.attrs/1` declares, never map
  order, and every option is written whether or not it differs from the default.
  Parsing a layout and serialising it again therefore returns the identical
  string, which is what makes the design pad's autosave a no-op when nothing
  changed.

  ## Entities

  Saxy supports no DTDs and expands no entities — an `&foo;` in a stored layout
  comes back as the literal text `&foo;` rather than whatever it was declared to
  mean. That is the reason this uses Saxy rather than `:xmerl`, whose scanner
  expands internal entities by default.
  """

  require Logger

  alias QuantumBilling.Settings.Organization
  alias QuantumBillingWeb.InvoiceDoc.Block
  alias QuantumBillingWeb.InvoiceDoc.Catalog
  alias QuantumBillingWeb.InvoiceDoc.Document

  @version 1

  @header """
  QuantumBilling invoice layout. Generated by the design pad; not hand-edited.
  Structure only. The accent colour and the logo are read live from the
  organisation, so rebranding restyles every invoice rather than only the next.\
  """

  @page_attrs [
    {"size", :size, {:enum, ~w(A4 Letter)}, "A4"},
    {"margin", :margin, {:enum, ~w(10mm 14mm 18mm 22mm)}, "14mm"},
    {"base-font", :base_font, :integer, 12},
    {"font", :font, {:enum, ~w(sans serif)}, "sans"}
  ]

  @doc "The layout schema version this module writes."
  def version, do: @version

  @doc """
  The page setup's attribute spec, in emit order.

  Exposed so the design pad's page controls cast through the same declarations
  the parser uses, rather than keeping a second list of what a margin may be.
  """
  def page_attrs, do: @page_attrs

  @doc """
  Parses stored layout XML.

  Unknown elements and unknown field names are dropped with a warning rather
  than failing the parse: a layout that has lost a block is still a usable
  document, whereas refusing to render an invoice because one attribute is
  unrecognised would take a customer's invoice off the screen.
  """
  @spec parse(binary()) :: {:ok, Document.t()} | {:error, String.t()}
  def parse(xml) when is_binary(xml) do
    case Saxy.SimpleForm.parse_string(xml) do
      {:ok, {"invoice-template", attrs, children}} ->
        with {:ok, version} <- parse_version(attrs) do
          {:ok,
           %Document{
             version: version,
             page: parse_page(children),
             blocks: parse_blocks(children)
           }}
        end

      {:ok, {other, _attrs, _children}} ->
        {:error, "This is not an invoice layout — its root element is <#{other}>."}

      {:error, %Saxy.ParseError{} = error} ->
        {:error, "This layout is not valid XML: #{Exception.message(error)}"}
    end
  end

  @doc """
  Parses or raises.

  For the stock layout and anything else built in this codebase, where a parse
  failure is a bug rather than bad data.
  """
  @spec parse!(binary()) :: Document.t()
  def parse!(xml) do
    case parse(xml) do
      {:ok, document} -> document
      {:error, message} -> raise ArgumentError, message
    end
  end

  @doc "Serialises a document back to XML."
  @spec to_xml(Document.t()) :: binary()
  def to_xml(%Document{} = document) do
    Saxy.encode!(document_tree(document), version: "1.0", encoding: :utf8) <> "\n"
  end

  @doc """
  Checks a document says enough to be an invoice.

  Presence rules only — anything a renderer can sensibly default is defaulted
  rather than rejected here.
  """
  @spec validate(Document.t()) :: :ok | {:error, [String.t()]}
  def validate(%Document{} = document) do
    missing_blocks =
      Catalog.required()
      |> Enum.reject(&Document.has_type?(document, &1))
      |> Enum.map(&"The #{humanise(&1)} block is required and is missing.")

    missing_columns =
      case Enum.find(document.blocks, &(&1.type == :items)) do
        nil ->
          []

        items ->
          present = Enum.map(items.children, & &1.field)

          Catalog.required_item_fields()
          |> Enum.reject(&(&1 in present))
          |> Enum.map(&"The item table must keep its #{humanise(&1)} column.")
      end

    case missing_blocks ++ missing_columns do
      [] -> :ok
      errors -> {:error, errors}
    end
  end

  @doc """
  The document equivalent to an organisation's `doc_*` customization columns.

  The bridge that lets the renderer replace three hand-written markups without
  changing what anybody's invoice looks like: every one of the old booleans is
  expressed here as the presence or absence of a block or a column.
  """
  @spec from_legacy(map()) :: Document.t()
  def from_legacy(%Organization{} = organization) do
    organization |> Map.from_struct() |> from_legacy()
  end

  # Takes a plain map rather than only the struct so the migration that drops
  # these columns can read them straight out of the database and preserve what
  # they said. By the time that migration runs the schema no longer declares the
  # fields, so a struct is not available to it.
  def from_legacy(settings) when is_map(settings) do
    Catalog.classic()
    |> put_heading(get(settings, :doc_heading))
    |> put_footer(get(settings, :doc_footer_text))
    |> drop_columns_unless(get(settings, :doc_show_hsn, true), "hsn_sac")
    |> drop_columns_unless(get(settings, :doc_show_unit, true), "unit")
    |> drop_columns_unless(get(settings, :doc_show_tax_rate, true), "tax_rate")
    |> drop_total_unless(get(settings, :doc_show_cess, false), "cess")
    |> drop_block_unless(get(settings, :doc_show_amount_words, true), :amount_in_words)
    |> drop_block_unless(get(settings, :doc_show_remarks, true), :remarks)
  end

  defp get(settings, key, default \\ nil) do
    case Map.get(settings, key, Map.get(settings, to_string(key), default)) do
      nil -> default
      value -> value
    end
  end

  defp put_heading(document, heading) do
    update_type(document, :heading, fn block ->
      %{block | opts: Map.put(block.opts, :text, heading || "")}
    end)
  end

  defp put_footer(document, nil), do: drop_type(document, :footer)
  defp put_footer(document, ""), do: drop_type(document, :footer)

  defp put_footer(document, text) do
    update_type(document, :footer, fn block -> %{block | text: text} end)
  end

  defp drop_columns_unless(document, true, _field), do: document

  defp drop_columns_unless(document, _falsey, field) do
    update_type(document, :items, fn block ->
      %{block | children: Enum.reject(block.children, &(&1.field == field))}
    end)
  end

  defp drop_total_unless(document, true, _field), do: document

  defp drop_total_unless(document, _falsey, field) do
    update_type(document, :totals, fn block ->
      %{block | children: Enum.reject(block.children, &(&1.field == field))}
    end)
  end

  defp drop_block_unless(document, true, _type), do: document
  defp drop_block_unless(document, _falsey, type), do: drop_type(document, type)

  defp drop_type(%Document{} = document, type) do
    %{document | blocks: Enum.reject(document.blocks, &(&1.type == type))}
  end

  defp update_type(%Document{} = document, type, fun) do
    blocks = Enum.map(document.blocks, fn b -> if b.type == type, do: fun.(b), else: b end)
    %{document | blocks: blocks}
  end

  # -- serialising ----------------------------------------------------------

  defp document_tree(%Document{} = document) do
    {"invoice-template", [{"version", Integer.to_string(document.version)}],
     [
       nl(1),
       {:comment, "\n  " <> @header <> "\n  "},
       nl(1),
       page_tree(document.page),
       nl(1),
       blocks_tree(document.blocks),
       nl(0)
     ]}
  end

  defp page_tree(page) do
    attrs =
      Enum.map(@page_attrs, fn {xml, key, kind, default} ->
        {xml, Catalog.dump_value(Map.get(page, key, default), kind)}
      end)

    {"page", attrs, []}
  end

  defp blocks_tree(blocks) do
    children =
      blocks
      |> Enum.flat_map(fn block -> [nl(2), block_tree(block)] end)
      |> Kernel.++([nl(1)])

    {"blocks", [], children}
  end

  defp block_tree(%Block{} = block) do
    attrs =
      [{"id", block.id}] ++
        Enum.map(Catalog.attrs(block.type), fn {xml, key, kind, default} ->
          {xml, Catalog.dump_value(Map.get(block.opts, key, default), kind)}
        end)

    {Catalog.element_name(block.type), attrs, block_children(block)}
  end

  # Text blocks carry exactly one child and no indentation: whitespace inside
  # them would become part of the printed footer.
  defp block_children(%Block{text: text} = block) when is_binary(text) do
    if text == "" and block.children == [], do: [], else: [{:characters, text}]
  end

  defp block_children(%Block{children: []}), do: []

  defp block_children(%Block{} = block) do
    name = Catalog.child_element(block.type)
    spec = Catalog.child_attrs(block.type)

    block.children
    |> Enum.flat_map(fn child -> [nl(3), child_tree(name, spec, child)] end)
    |> Kernel.++([nl(2)])
  end

  defp child_tree(name, spec, child) do
    attrs =
      Enum.map(spec, fn {xml, key, kind, default} ->
        {xml, Catalog.dump_value(Map.get(child, key, default), kind)}
      end)

    {name, attrs, []}
  end

  defp nl(depth), do: "\n" <> String.duplicate("  ", depth)

  # -- parsing --------------------------------------------------------------

  defp parse_version(attrs) do
    case attr(attrs, "version") do
      nil ->
        {:ok, @version}

      raw ->
        case Integer.parse(raw) do
          {n, ""} when n >= 1 and n <= @version ->
            {:ok, n}

          {n, ""} when n > @version ->
            {:error,
             "This layout was made by a newer version of QuantumBilling (version #{n}) " <>
               "and cannot be opened here."}

          _other ->
            {:error, "The layout's version is not a number."}
        end
    end
  end

  defp parse_page(children) do
    attrs =
      case Enum.find(elements(children), fn {name, _a, _c} -> name == "page" end) do
        {_name, attrs, _children} -> attrs
        nil -> []
      end

    Map.new(@page_attrs, fn {xml, key, kind, default} ->
      {key, read_attr(attrs, xml, kind, default)}
    end)
  end

  defp parse_blocks(children) do
    case Enum.find(elements(children), fn {name, _a, _c} -> name == "blocks" end) do
      {_name, _attrs, block_children} ->
        block_children
        |> elements()
        |> Enum.map(&parse_block/1)
        |> Enum.reject(&is_nil/1)
        |> assign_ids()

      nil ->
        []
    end
  end

  defp parse_block({name, attrs, children}) do
    case Catalog.type_for(name) do
      nil ->
        Logger.warning("Ignoring unknown invoice layout block <#{name}>")
        nil

      type ->
        %Block{
          type: type,
          id: attr(attrs, "id"),
          opts: parse_opts(type, attrs),
          children: parse_children(type, children),
          text: parse_text(type, children)
        }
    end
  end

  defp parse_opts(type, attrs) do
    Map.new(Catalog.attrs(type), fn {xml, key, kind, default} ->
      {key, read_attr(attrs, xml, kind, default)}
    end)
  end

  defp parse_children(type, children) do
    case Catalog.child_element(type) do
      nil ->
        []

      name ->
        spec = Catalog.child_attrs(type)
        allowed = Catalog.child_fields(type)

        children
        |> elements()
        |> Enum.filter(fn {n, _a, _c} -> n == name end)
        |> Enum.map(fn {_n, attrs, _c} -> parse_child(spec, attrs, allowed) end)
        |> Enum.reject(&is_nil/1)
    end
  end

  defp parse_child(spec, attrs, allowed) do
    field = attr(attrs, "field")

    if field in allowed do
      Map.new(spec, fn {xml, key, kind, default} ->
        {key, read_attr(attrs, xml, kind, default)}
      end)
    else
      Logger.warning("Ignoring unknown invoice layout field #{inspect(field)}")
      nil
    end
  end

  defp parse_text(type, children) when type in [:signature, :footer] do
    children
    |> Enum.filter(&is_binary/1)
    |> Enum.join()
  end

  defp parse_text(_type, _children), do: nil

  # A layout whose ids were lost or duplicated still has to be editable: the
  # pad addresses blocks by id, and two blocks sharing one would move together.
  defp assign_ids(blocks) do
    {blocks, _taken} =
      Enum.map_reduce(blocks, MapSet.new(), fn block, taken ->
        id =
          if is_binary(block.id) and block.id != "" and not MapSet.member?(taken, block.id) do
            block.id
          else
            Enum.find_value(1..1_000, fn n ->
              if !MapSet.member?(taken, "b#{n}"), do: "b#{n}"
            end)
          end

        {%{block | id: id}, MapSet.put(taken, id)}
      end)

    blocks
  end

  defp elements(children) do
    Enum.filter(children, fn
      {name, _attrs, _children} when is_binary(name) -> true
      _other -> false
    end)
  end

  defp attr(attrs, name) do
    Enum.find_value(attrs, fn {key, value} -> if key == name, do: value end)
  end

  defp read_attr(attrs, name, kind, default) do
    case attr(attrs, name) do
      nil ->
        default

      raw ->
        case Catalog.cast_value(raw, kind) do
          {:ok, value} -> value
          :error -> default
        end
    end
  end

  defp humanise(value) do
    value |> to_string() |> String.replace("_", " ")
  end
end
